import { createHash } from 'node:crypto';
import { mkdtempSync, readFileSync, readdirSync, rmSync, statSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { afterAll, beforeAll, beforeEach, describe, expect, it } from 'vitest';
import {
  GitEngine,
  GitHubExtension,
  githubRepository,
  sanitizeTitle,
} from '../../src/git/index.js';
import {
  API_TOKEN,
  GIT_TOKEN,
  NAME,
  OWNER,
  diffOf,
  lookup,
  makeDispatcher,
  makeTls,
  secretsFor,
  seedRepo,
  startFakeServer,
  type FakeServer,
  type Tls,
} from './fixtures.js';

let tmp: string;
let tls: Tls;
let srv: FakeServer;
const audits: Record<string, unknown>[] = [];

const ext = (over: Record<string, unknown> = {}) =>
  new GitHubExtension({
    dispatcher: makeDispatcher(tls.cert),
    secrets: secretsFor(),
    tokenRef: 'api-token',
    repositoryUrl: srv.url,
    privateAllow: ['127.0.0.1'],
    lookup,
    audit: (e) => void audits.push(e),
    ...over,
  });

beforeAll(async () => {
  tmp = mkdtempSync(path.join(tmpdir(), 'oax-gh-test-'));
  tls = makeTls(tmp);
  srv = await startFakeServer(tls, { git: GIT_TOKEN, api: API_TOKEN });
});

afterAll(async () => {
  await srv.close();
  rmSync(tmp, { recursive: true, force: true });
});

beforeEach(() => {
  srv.pulls.length = 0;
  srv.posted.length = 0;
  srv.seen.length = 0;
  audits.length = 0;
  Object.assign(srv.mode, {
    apiStatus: undefined,
    apiNonDraft: false,
    apiRedirect: false,
    apiBigBody: false,
    pageSize: undefined,
  });
});

const HEAD = 'oax/bug-fix/issue-7-abcd1234';
const input = (over: Record<string, unknown> = {}) => ({
  head: HEAD,
  title: 'fix: round discounts half up',
  body: '> Rounds half up.\n\nAI-generated by the openagentix bug-fix agent; review before merging.',
  ...over,
});

describe('GitHubExtension', () => {
  it('derives the repository and API bases by fixed rules', () => {
    expect(githubRepository('https://github.com/open-agentix/dogfood-sandbox')).toMatchObject({
      full: 'open-agentix/dogfood-sandbox',
      apiBase: 'https://api.github.com',
      htmlBase: 'https://github.com',
    });
    expect(githubRepository('https://ghe.example.org/o/r.git')).toMatchObject({
      full: 'o/r',
      apiBase: 'https://ghe.example.org/api/v3',
    });
    expect(() => githubRepository('https://github.com/a/b/c')).toThrow();
    expect(() => githubRepository('http://github.com/a/b')).toThrow();
  });

  it('opens a draft pull request and reduces the answer', async () => {
    const ref = await ext().openDraftPullRequest(input());
    expect(ref).toEqual({
      number: 101,
      url: `https://localhost:${srv.port}/${OWNER}/${NAME}/pull/101`,
      state: 'open',
      draft: true,
    });
    expect(srv.posted).toHaveLength(1);
    expect(srv.posted[0]).toEqual({
      title: 'fix: round discounts half up',
      head: HEAD,
      base: 'main',
      body: input().body,
      draft: true,
      maintainer_can_modify: false,
    });
    const a = audits.find((x) => x.action === 'git.pr_open');
    expect(a).toMatchObject({ ok: true, number: 101, head: HEAD });
    expect(JSON.stringify(audits)).not.toContain(API_TOKEN);
    expect(JSON.stringify(audits)).not.toContain('Rounds half up');
  });

  it('only ever talks to the configured repository and with the extension credential', async () => {
    await ext().openDraftPullRequest(input());
    const api = srv.seen.filter((r) => r.url.startsWith('/api/'));
    expect(api.length).toBeGreaterThan(0);
    for (const r of api) {
      expect(r.url.split('?')[0]).toBe(`/api/v3/repos/${OWNER}/${NAME}/pulls`);
      expect(['GET', 'POST']).toContain(r.method);
      expect(r.auth).toBe(`Bearer ${API_TOKEN}`);
      expect(r.auth).not.toContain(GIT_TOKEN);
    }
  });

  it('forces the base and the draft flag and checks the head', async () => {
    const e = ext();
    await expect(e.openDraftPullRequest(input({ base: 'release' }))).rejects.toMatchObject({
      code: 'target_invalid',
    });
    for (const head of [
      'main',
      'oax/other/x',
      'oax/bug-fix/',
      'oax/bug-fix/../main',
      'oax/bug-fix/a b',
      '-oax/bug-fix/x',
      'oax/bug-fix/x.lock',
      'refs/heads/oax/bug-fix/x',
      'oax/bug-fix//x',
    ])
      await expect(e.openDraftPullRequest(input({ head })), head).rejects.toMatchObject({
        code: 'branch_prefix_refused',
      });
    expect(srv.posted).toHaveLength(0);
    await e.openDraftPullRequest(input({ base: 'main' }));
    expect((srv.posted[0] as { draft: boolean }).draft).toBe(true);
  });

  it('sanitises the title and caps the body', async () => {
    expect(sanitizeTitle('  fix:\n\tx\u0000y  ' + 'z'.repeat(100))).toHaveLength(72);
    expect(sanitizeTitle('a\nb')).toBe('a b');
    await expect(ext().openDraftPullRequest(input({ title: ' \n ' }))).rejects.toMatchObject({
      code: 'target_invalid',
    });
    await expect(
      ext({ maxBodyBytes: 100 }).openDraftPullRequest(input({ body: 'x'.repeat(101) })),
    ).rejects.toMatchObject({
      code: 'pr_body_too_large',
    });
    expect(srv.posted).toHaveLength(0);
  });

  it('blocks credential-like text in title and body before anything is sent', async () => {
    const bodies = [
      `see ghp_${'R'.repeat(36)}`,
      `token ${API_TOKEN}`,
      Buffer.from(API_TOKEN).toString('base64'),
      '-----BEGIN RSA PRIVATE KEY-----',
    ];
    for (const body of bodies)
      await expect(ext().openDraftPullRequest(input({ body })), body).rejects.toMatchObject({
        code: 'secret_detected',
      });
    await expect(
      ext().openDraftPullRequest(input({ title: `fix ghp_${'R'.repeat(36)}` })),
    ).rejects.toMatchObject({
      code: 'secret_detected',
    });
    expect(srv.seen.filter((r) => r.method === 'POST')).toHaveLength(0);
    expect(JSON.stringify(audits)).not.toContain(API_TOKEN);
  });

  it('counts open pull requests per prefix before creating and stops at the limit', async () => {
    srv.pulls.push(
      { number: 1, head: 'oax/bug-fix/a', draft: true },
      { number: 2, head: 'oax/bug-fix/b', draft: true },
      { number: 3, head: 'oax/other/c', draft: true },
      { number: 4, head: 'oax/bug-fix/fork', repo: 'someone/else', draft: true },
      { number: 5, head: 'feature/x', draft: false },
    );
    const e = ext();
    expect(await e.countOpenPullRequests('oax/bug-fix/')).toBe(2);
    expect(await e.countOpenPullRequests('oax/other/')).toBe(1);
    await expect(e.openDraftPullRequest(input())).rejects.toMatchObject({
      code: 'pr_limit_reached',
    });
    expect(srv.posted).toHaveLength(0);
    // a higher limit lets it through
    await ext({ maxOpenPullRequests: 3 }).openDraftPullRequest(input());
    expect(srv.posted).toHaveLength(1);
  });

  it('pages through the list and serialises concurrent creations', async () => {
    for (let i = 1; i <= 120; i++)
      srv.pulls.push({ number: i, head: `oax/other/${i}`, draft: true });
    expect(await ext().countOpenPullRequests('oax/other/')).toBe(120);
    srv.pulls.length = 0;
    const e = ext();
    const results = await Promise.allSettled(
      [1, 2, 3, 4].map((i) => e.openDraftPullRequest(input({ head: `oax/bug-fix/c-${i}` }))),
    );
    expect(results.filter((r) => r.status === 'fulfilled')).toHaveLength(2);
    expect(results.filter((r) => r.status === 'rejected')).toHaveLength(2);
    expect(srv.posted).toHaveLength(2);
  });

  it('refuses answers that are not a draft pull request of this repository', async () => {
    srv.mode.apiNonDraft = true;
    await expect(ext().openDraftPullRequest(input())).rejects.toMatchObject({
      code: 'host_response_invalid',
    });
  });

  it('maps host failures to fixed codes without host text', async () => {
    srv.mode.apiStatus = 500;
    const e = await ext()
      .openDraftPullRequest(input())
      .catch((x: Error) => x);
    expect(e).toMatchObject({ code: 'host_request_failed' });
    expect(String((e as Error).message)).not.toContain('ghp_leaky');
    srv.mode.apiStatus = 404;
    await expect(ext().openDraftPullRequest(input())).rejects.toMatchObject({ code: 'not_found' });
    srv.mode.apiStatus = undefined;
    await expect(
      ext({ secrets: { resolve: async () => 'wrong-token-value-123456' } }).openDraftPullRequest(
        input(),
      ),
    ).rejects.toMatchObject({ code: 'auth_failed' });
    await expect(
      ext({
        secrets: {
          resolve: async () => {
            throw new Error('nope');
          },
        },
      }).openDraftPullRequest(input()),
    ).rejects.toMatchObject({ code: 'credential_unavailable' });
  });

  it('never follows redirects and caps the response size', async () => {
    srv.mode.apiRedirect = true;
    await expect(ext().countOpenPullRequests()).rejects.toMatchObject({
      code: 'host_request_failed',
    });
    expect(srv.seen.some((r) => r.url.startsWith('/elsewhere'))).toBe(false);
    srv.mode.apiRedirect = false;
    srv.mode.apiBigBody = true;
    await expect(ext().openDraftPullRequest(input())).rejects.toMatchObject({
      code: 'host_response_invalid',
    });
  });

  it('is denied by the resolver for unlisted private addresses', async () => {
    await expect(ext({ privateAllow: [] }).countOpenPullRequests()).rejects.toMatchObject({
      code: 'egress_denied',
    });
  });

  it('validates its configuration', () => {
    expect(() => ext({ branchPrefix: 'feature/' })).toThrow();
    expect(() => ext({ branchPrefix: 'oax/' })).toThrow();
    expect(() => ext({ maxOpenPullRequests: 0 })).toThrow();
    expect(() => ext({ maxOpenPullRequests: 50 })).toThrow();
    expect(() => ext({ baseBranch: '../x' })).toThrow();
  });
});

describe('end to end: engine and extension with separate credentials', () => {
  it('pushes a branch with the git credential and opens the draft PR with the API credential', async () => {
    const PRICE_BEFORE = 'export const x = 1;\n';
    const PRICE_AFTER = 'export const x = 2;\n';
    const sha = seedRepo(srv, { 'src/price.js': PRICE_BEFORE }, { branch: 'e2e' });
    const engine = new GitEngine({
      dispatcher: makeDispatcher(tls.cert),
      secrets: secretsFor(),
      secretReader: (r) => (r === 'test-ca' ? tls.cert : undefined),
      privateAllow: ['127.0.0.1'],
      lookup,
      tmpRoot: tmp,
    });
    const s = await engine.openSession({
      url: srv.url,
      credential: { tokenRef: 'git-token', username: 'x-access-token' },
      branchPrefix: 'oax/bug-fix/',
    });
    try {
      await s.fetchCommit(sha);
      const patch = diffOf('src/price.js', PRICE_BEFORE, PRICE_AFTER);
      const rep = await s.applyAndPushBranch({
        sha,
        patch,
        patchSha256: createHash('sha256').update(patch).digest('hex'),
        branch: HEAD,
        message: 'fix(price): bump value',
        identity: { name: 'agentix-zero', email: 'github@openagentix.si' },
      });
      expect(rep.pushed).toBe(true);
      const pr = await ext().openDraftPullRequest(input());
      expect(pr.draft).toBe(true);
    } finally {
      await s.dispose();
    }
    const gitReqs = srv.seen.filter((r) => !r.url.startsWith('/api/'));
    const apiReqs = srv.seen.filter((r) => r.url.startsWith('/api/'));
    expect(gitReqs.length).toBeGreaterThan(0);
    for (const r of gitReqs) expect(r.auth).toContain('Basic');
    for (const r of apiReqs) expect(r.auth).toBe(`Bearer ${API_TOKEN}`);
    expect(gitReqs.some((r) => r.auth?.includes(API_TOKEN))).toBe(false);
  });
});

describe('source tree guard: no completion, review, label or dispatch call can exist', () => {
  const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../src/git');
  const files = (dir: string): string[] =>
    readdirSync(dir).flatMap((n) => {
      const p = path.join(dir, n);
      return statSync(p).isDirectory() ? files(p) : p.endsWith('.ts') ? [p] : [];
    });

  const FORBIDDEN: [string, RegExp][] = [
    ['merge endpoint', /\/merge\b/i],
    ['merge method', /merge_method|mergeMethod|commit_title/i],
    ['auto merge', /auto_?merge|enableAutoMerge/i],
    ['merge function', /\b(?:merge|mergePull|mergePullRequest|squash|rebaseMerge)\w*\s*\(/],
    ['review endpoint', /\/reviews?\b|\/requested_reviewers|\/approve/i],
    ['labels endpoint', /\/labels\b/i],
    ['workflow dispatch', /\/dispatches\b|workflow_dispatch|\/actions\//i],
    ['graphql', /graphql/i],
    ['pull update (close/edit)', /'PATCH'|"PATCH"|'PUT'|"PUT"|'DELETE'|"DELETE"/],
    ['pull endpoint with number', /\/pulls\/\$\{|\/pulls\/\d/],
    ['branch deletion or force', /--force|--delete|--mirror|\+refs\/|git\/refs/],
  ];

  it('finds the sources', () => {
    expect(files(root).length).toBeGreaterThanOrEqual(8);
  });

  it.each(FORBIDDEN)('contains no %s', (_label, re) => {
    const hits = files(root).filter((f) => re.test(readFileSync(f, 'utf8')));
    expect(hits.map((f) => path.relative(root, f))).toEqual([]);
  });

  it('exports no merge, review, label or workflow function', async () => {
    const mod = await import('../../src/git/index.js');
    const names = Object.keys(mod).concat(
      Object.getOwnPropertyNames(mod.GitHubExtension.prototype),
    );
    expect(
      names.filter((n) => /merge|review|label|dispatch|approve|close|delete|force/i.test(n)),
    ).toEqual([]);
  });

  it('allows exactly GET and POST on the pulls path in the extension', () => {
    const src = readFileSync(path.join(root, 'github.ts'), 'utf8');
    expect(src.match(/'(?:GET|POST|PUT|PATCH|DELETE|HEAD)'/g)?.sort()).toEqual(
      ["'GET'", "'GET'", "'POST'", "'POST'"].sort(),
    );
    expect(src.match(/\/repos\/\$\{/g)).toHaveLength(1);
  });
});
