import type { FastifyInstance } from 'fastify';
import { stringify } from 'yaml';

/** Renders the OpenAPI 3.1 document of a built app as YAML (committed as /openapi.yaml). */
export function renderOpenApi(app: FastifyInstance): string {
  const doc = app.swagger() as unknown as Record<string, unknown>;
  // Servers depend on deployment configuration; the committed document uses a placeholder.
  const stable = {
    ...doc,
    servers: [{ url: 'http://localhost:8080', description: 'local development' }],
  };
  return `# Generated by \`pnpm --filter @openagentix/api openapi\` - do not edit by hand.\n${stringify(stable, { lineWidth: 0, aliasDuplicateObjects: false })}`;
}
