import { randomBytes, timingSafeEqual } from 'node:crypto';
import { createServer, type IncomingMessage, type Server as HttpServer } from 'node:http';
import type { AddressInfo } from 'node:net';
import { StreamableHTTPServerTransport } from '@modelcontextprotocol/sdk/server/streamableHttp.js';
import { createPolicyGateServer, type GateServerOptions } from './gate-server.js';

export interface GateHttpOptions extends GateServerOptions {
  /** Bearer token the harness must present; a random one is generated by default. */
  token?: string;
  /** Loopback by default: the gate is only meant for a harness on the same host. */
  host?: string;
  maxBodyBytes?: number;
}

export interface GateHttpHandle {
  /** `http://127.0.0.1:<port>/mcp` */
  url: string;
  token: string;
  close(): Promise<void>;
}

function authorized(req: IncomingMessage, token: string): boolean {
  const got = Buffer.from(req.headers.authorization ?? '');
  const want = Buffer.from(`Bearer ${token}`);
  return got.length === want.length && timingSafeEqual(got, want);
}

async function readBody(req: IncomingMessage, max: number): Promise<unknown> {
  const chunks: Buffer[] = [];
  let size = 0;
  for await (const c of req) {
    size += (c as Buffer).length;
    if (size > max) throw new Error('payload too large');
    chunks.push(c as Buffer);
  }
  return JSON.parse(Buffer.concat(chunks).toString('utf8')) as unknown;
}

/**
 * Serves the policy gate as a stateless streamable-HTTP MCP endpoint ("MCP bridge") so an
 * external harness running on this host can use it as its only tool source. Every request needs
 * the bearer token; every tool call is decided by the policy gate and reported through `onCall`.
 */
export async function serveGateHttp(opts: GateHttpOptions): Promise<GateHttpHandle> {
  const token = opts.token ?? randomBytes(32).toString('base64url');
  const max = opts.maxBodyBytes ?? 1_048_576;
  const http: HttpServer = createServer((req, res) => {
    void (async () => {
      const send = (status: number, body: unknown) => {
        res.writeHead(status, { 'content-type': 'application/json' });
        res.end(JSON.stringify(body));
      };
      if (!authorized(req, token)) return send(401, { error: 'unauthenticated' });
      if (req.url?.split('?')[0] !== '/mcp') return send(404, { error: 'not_found' });
      if (req.method !== 'POST') return send(405, { error: 'method_not_allowed' });
      let body: unknown;
      try {
        body = await readBody(req, max);
      } catch {
        return send(400, { error: 'invalid_body' });
      }
      const server = createPolicyGateServer(opts);
      const transport = new StreamableHTTPServerTransport({
        sessionIdGenerator: undefined,
        enableJsonResponse: true,
      });
      res.on('close', () => {
        void transport.close();
        void server.close();
      });
      await server.connect(transport);
      await transport.handleRequest(req, res, body);
    })().catch(() => {
      if (!res.headersSent) res.writeHead(500, { 'content-type': 'application/json' });
      res.end(JSON.stringify({ error: 'internal_error' }));
    });
  });
  await new Promise<void>((resolve, reject) => {
    http.once('error', reject);
    http.listen(0, opts.host ?? '127.0.0.1', resolve);
  });
  const { port } = http.address() as AddressInfo;
  return {
    url: `http://${opts.host ?? '127.0.0.1'}:${port}/mcp`,
    token,
    close: () =>
      new Promise<void>((resolve) => {
        http.closeAllConnections();
        http.close(() => resolve());
      }),
  };
}
