// Generates typed API definitions from the control node's OpenAPI contract.
// Usage: pnpm gen:api            (reads ../../openapi.yaml)
//        OPENAPI_FILE=path pnpm gen:api
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import openapiTS, { astToString } from 'openapi-typescript';

const here = dirname(fileURLToPath(import.meta.url));
const input = resolve(here, '..', process.env.OPENAPI_FILE ?? '../../openapi.yaml');
const output = resolve(here, '../src/api/schema.d.ts');

if (!existsSync(input)) {
  console.error(`OpenAPI file not found: ${input} (set OPENAPI_FILE)`);
  process.exit(1);
}

const ast = await openapiTS(pathToFileURL(input), { alphabetize: false, rootTypes: false });
const header = '// Generated by `pnpm gen:api` from openapi.yaml - do not edit by hand.\n\n';
const content = header + astToString(ast);
const previous = existsSync(output) ? readFileSync(output, 'utf8') : '';
writeFileSync(output, content);
console.warn(previous === content ? `unchanged: ${output}` : `written: ${output}`);
